/*
 * main_read_test.cpp
 *
 * Example usage file for the refactored NAU7802 driver.
 * This example initializes the sensor with 1x gain
 * and continuously reads the raw ADC value.
 */

/* Includes ------------------------------------------------------------------*/
#include "main.h"
#include "i2c_wrapper.hpp"
#include "NAU7802.hpp"
#include <stdio.h> // For printf debugging

/* Private variables ---------------------------------------------------------*/
// Assume hi2c1 is generated by STM32CubeIDE and initialized in main()
extern I2C_HandleTypeDef hi2c1; 

/* Function Prototypes -------------------------------------------------------*/
// These are assumed to be in main.h or defined in main.c
void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_I2C1_Init(void); 
extern void Error_Handler(void); 

/**
  * @brief  The application entry point.
  */
int main(void)
{
  /* MCU Configuration--------------------------------------------------------*/
  HAL_Init();
  SystemClock_Config();
  MX_GPIO_Init();
  MX_I2C1_Init(); // This initializes hi2c1
  MC_UART_Init();
  /* --- SETUP STAGE --- */
  // 1. Create wrapper instance
  I2C_Wrapper i2c_bus_1(&hi2c1);
  
  // 2. Create data output struct
  NAU7802_OUT adc_data;
  
  // 3. Create the driver object
  // Pass the address of the wrapper and the HAL_Delay function pointer
  NAU7802 adc(&i2c_bus_1);

  // 4. Initialize the sensor
  // Initializing with 1x Gain. Options: NAU7802_GAIN_1X through _128X
  if (adc.begin(NAU7802_GAIN_1X) != NauStatus::OK) 
  {
    // ADC not found or failed to configure
    Error_Handler();
  }
  
  // 5. Calibration (Optional)
  // Recommended to run after power-up and stabilization.
  // adc.calibrate(); // Un-comment when calibration logic is fully verified

  /* --- MAIN LOOP --- */
  while (1)
  {
    // 6. Check if data is ready
    if (adc.isReady()) 
    {
      // 7. Read data
      if (adc.readSensor(&adc_data) == NauStatus::OK)
      {
        // Debug print usage:
        // printf("Raw ADC Value: %ld\r\n", adc_data.raw_reading);
      }
    }
    HAL_Delay(100); // Wait 100ms before checking again
  }
}
